name: CI

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.2.1
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      elasticsearch:
        image: elasticsearch:9.2.0
        env:
          discovery.type: single-node
          xpack.security.enabled: false
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew clean test jacocoTestReport -Dspring.profiles.active=test -Dspring.data.redis.host=redis -Dspring.data.redis.port=6379 -Dspring.elasticsearch.uris=http://elasticsearch:9200

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
